import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import HeaderNav from "../components/HeaderNav";

const Home: NextPage = () => {
  return (
    <div className="h-screen w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HeaderNav />
    </div>
  );
};

export default Home;
